"""Add owner column

Revision ID: 1058d61bdaff
Revises: 4023b8b2a06d
Create Date: 2026-06-25 18:04:03.239249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1058d61bdaff'
down_revision: Union[str, Sequence[str], None] = '4023b8b2a06d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car_dealers', sa.Column('owner', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('car_dealers', 'owner')
    # ### end Alembic commands ###
